/** Generated by scripts/generate-role-icon-catalog.mjs — do not edit manually. */
import type { AppIcon } from './types'

export const ROLE_ICONS: AppIcon[] = [
  { id: 'role-accountant', label: 'Accountant', path: '/icons/pharmacy-roles/accountant.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2101 },
  { id: 'role-administrator', label: 'Administrator', path: '/icons/pharmacy-roles/administrator.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2102 },
  { id: 'role-cashier', label: 'Cashier', path: '/icons/pharmacy-roles/cashier.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2103 },
  { id: 'role-cleaner-maintenance', label: 'Cleaner Maintenance', path: '/icons/pharmacy-roles/cleaner-maintenance.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2104 },
  { id: 'role-compounding-technician', label: 'Compounding Technician', path: '/icons/pharmacy-roles/compounding-technician.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2105 },
  { id: 'role-customer-service', label: 'Customer Service', path: '/icons/pharmacy-roles/customer-service.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2106 },
  { id: 'role-delivery-courier', label: 'Delivery Courier', path: '/icons/pharmacy-roles/delivery-courier.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2107 },
  { id: 'role-generic-employee', label: 'Generic Employee', path: '/icons/pharmacy-roles/generic-employee.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2108 },
  { id: 'role-hr-personnel', label: 'Hr Personnel', path: '/icons/pharmacy-roles/hr-personnel.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2109 },
  { id: 'role-inventory-manager', label: 'Inventory Manager', path: '/icons/pharmacy-roles/inventory-manager.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2110 },
  { id: 'role-manager', label: 'Manager', path: '/icons/pharmacy-roles/manager.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2111 },
  { id: 'role-medical-advisor', label: 'Medical Advisor', path: '/icons/pharmacy-roles/medical-advisor.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2112 },
  { id: 'role-owner', label: 'Owner', path: '/icons/pharmacy-roles/owner.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2113 },
  { id: 'role-pharmacist', label: 'Pharmacist', path: '/icons/pharmacy-roles/pharmacist.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2114 },
  { id: 'role-pharmacy-clerk', label: 'Pharmacy Clerk', path: '/icons/pharmacy-roles/pharmacy-clerk.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2115 },
  { id: 'role-purchasing', label: 'Purchasing', path: '/icons/pharmacy-roles/purchasing.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2116 },
  { id: 'role-sales-associate', label: 'Sales Associate', path: '/icons/pharmacy-roles/sales-associate.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2117 },
  { id: 'role-security', label: 'Security', path: '/icons/pharmacy-roles/security.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2118 },
  { id: 'role-shift-supervisor', label: 'Shift Supervisor', path: '/icons/pharmacy-roles/shift-supervisor.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2119 },
  { id: 'role-trainee', label: 'Trainee', path: '/icons/pharmacy-roles/trainee.png', entityTypes: ['company_role'], tags: ['pharmacy'], sortOrder: 2120 },
]

export const DEFAULT_ROLE_ICON_ID = 'role-manager' as const
