-- Personnel avatars (male/female) + avatar_gender on people entities.

create type public.avatar_gender as enum ('male', 'female');

alter table public.app_icons
  add column avatar_gender public.avatar_gender;

alter table public.personnel
  add column avatar_gender public.avatar_gender not null default 'female';

insert into public.app_icons (id, label, path, entity_types, tags, sort_order, avatar_gender) values
  ('avatar-male-001', 'Male avatar 1', '/avatars/male/avatar_001.png', array['personnel']::public.icon_entity_type[], '{male}', 1001, 'male'),
  ('avatar-male-003', 'Male avatar 3', '/avatars/male/avatar_003.png', array['personnel']::public.icon_entity_type[], '{male}', 1003, 'male'),
  ('avatar-male-006', 'Male avatar 6', '/avatars/male/avatar_006.png', array['personnel']::public.icon_entity_type[], '{male}', 1006, 'male'),
  ('avatar-male-008', 'Male avatar 8', '/avatars/male/avatar_008.png', array['personnel']::public.icon_entity_type[], '{male}', 1008, 'male'),
  ('avatar-male-009', 'Male avatar 9', '/avatars/male/avatar_009.png', array['personnel']::public.icon_entity_type[], '{male}', 1009, 'male'),
  ('avatar-male-011', 'Male avatar 11', '/avatars/male/avatar_011.png', array['personnel']::public.icon_entity_type[], '{male}', 1011, 'male'),
  ('avatar-male-012', 'Male avatar 12', '/avatars/male/avatar_012.png', array['personnel']::public.icon_entity_type[], '{male}', 1012, 'male'),
  ('avatar-male-014', 'Male avatar 14', '/avatars/male/avatar_014.png', array['personnel']::public.icon_entity_type[], '{male}', 1014, 'male'),
  ('avatar-male-016', 'Male avatar 16', '/avatars/male/avatar_016.png', array['personnel']::public.icon_entity_type[], '{male}', 1016, 'male'),
  ('avatar-male-021', 'Male avatar 21', '/avatars/male/avatar_021.png', array['personnel']::public.icon_entity_type[], '{male}', 1021, 'male'),
  ('avatar-male-022', 'Male avatar 22', '/avatars/male/avatar_022.png', array['personnel']::public.icon_entity_type[], '{male}', 1022, 'male'),
  ('avatar-male-023', 'Male avatar 23', '/avatars/male/avatar_023.png', array['personnel']::public.icon_entity_type[], '{male}', 1023, 'male'),
  ('avatar-male-024', 'Male avatar 24', '/avatars/male/avatar_024.png', array['personnel']::public.icon_entity_type[], '{male}', 1024, 'male'),
  ('avatar-male-026', 'Male avatar 26', '/avatars/male/avatar_026.png', array['personnel']::public.icon_entity_type[], '{male}', 1026, 'male'),
  ('avatar-male-029', 'Male avatar 29', '/avatars/male/avatar_029.png', array['personnel']::public.icon_entity_type[], '{male}', 1029, 'male'),
  ('avatar-male-030', 'Male avatar 30', '/avatars/male/avatar_030.png', array['personnel']::public.icon_entity_type[], '{male}', 1030, 'male'),
  ('avatar-male-031', 'Male avatar 31', '/avatars/male/avatar_031.png', array['personnel']::public.icon_entity_type[], '{male}', 1031, 'male'),
  ('avatar-male-032', 'Male avatar 32', '/avatars/male/avatar_032.png', array['personnel']::public.icon_entity_type[], '{male}', 1032, 'male'),
  ('avatar-male-033', 'Male avatar 33', '/avatars/male/avatar_033.png', array['personnel']::public.icon_entity_type[], '{male}', 1033, 'male'),
  ('avatar-male-034', 'Male avatar 34', '/avatars/male/avatar_034.png', array['personnel']::public.icon_entity_type[], '{male}', 1034, 'male'),
  ('avatar-male-035', 'Male avatar 35', '/avatars/male/avatar_035.png', array['personnel']::public.icon_entity_type[], '{male}', 1035, 'male'),
  ('avatar-male-036', 'Male avatar 36', '/avatars/male/avatar_036.png', array['personnel']::public.icon_entity_type[], '{male}', 1036, 'male'),
  ('avatar-male-037', 'Male avatar 37', '/avatars/male/avatar_037.png', array['personnel']::public.icon_entity_type[], '{male}', 1037, 'male'),
  ('avatar-male-038', 'Male avatar 38', '/avatars/male/avatar_038.png', array['personnel']::public.icon_entity_type[], '{male}', 1038, 'male'),
  ('avatar-male-039', 'Male avatar 39', '/avatars/male/avatar_039.png', array['personnel']::public.icon_entity_type[], '{male}', 1039, 'male'),
  ('avatar-male-040', 'Male avatar 40', '/avatars/male/avatar_040.png', array['personnel']::public.icon_entity_type[], '{male}', 1040, 'male'),
  ('avatar-male-041', 'Male avatar 41', '/avatars/male/avatar_041.png', array['personnel']::public.icon_entity_type[], '{male}', 1041, 'male'),
  ('avatar-male-042', 'Male avatar 42', '/avatars/male/avatar_042.png', array['personnel']::public.icon_entity_type[], '{male}', 1042, 'male'),
  ('avatar-male-057', 'Male avatar 57', '/avatars/male/avatar_057.png', array['personnel']::public.icon_entity_type[], '{male}', 1057, 'male'),
  ('avatar-male-059', 'Male avatar 59', '/avatars/male/avatar_059.png', array['personnel']::public.icon_entity_type[], '{male}', 1059, 'male'),
  ('avatar-male-060', 'Male avatar 60', '/avatars/male/avatar_060.png', array['personnel']::public.icon_entity_type[], '{male}', 1060, 'male'),
  ('avatar-male-061', 'Male avatar 61', '/avatars/male/avatar_061.png', array['personnel']::public.icon_entity_type[], '{male}', 1061, 'male'),
  ('avatar-male-064', 'Male avatar 64', '/avatars/male/avatar_064.png', array['personnel']::public.icon_entity_type[], '{male}', 1064, 'male'),
  ('avatar-male-065', 'Male avatar 65', '/avatars/male/avatar_065.png', array['personnel']::public.icon_entity_type[], '{male}', 1065, 'male'),
  ('avatar-male-066', 'Male avatar 66', '/avatars/male/avatar_066.png', array['personnel']::public.icon_entity_type[], '{male}', 1066, 'male'),
  ('avatar-male-067', 'Male avatar 67', '/avatars/male/avatar_067.png', array['personnel']::public.icon_entity_type[], '{male}', 1067, 'male'),
  ('avatar-male-068', 'Male avatar 68', '/avatars/male/avatar_068.png', array['personnel']::public.icon_entity_type[], '{male}', 1068, 'male'),
  ('avatar-male-069', 'Male avatar 69', '/avatars/male/avatar_069.png', array['personnel']::public.icon_entity_type[], '{male}', 1069, 'male'),
  ('avatar-male-070', 'Male avatar 70', '/avatars/male/avatar_070.png', array['personnel']::public.icon_entity_type[], '{male}', 1070, 'male'),
  ('avatar-male-071', 'Male avatar 71', '/avatars/male/avatar_071.png', array['personnel']::public.icon_entity_type[], '{male}', 1071, 'male'),
  ('avatar-male-073', 'Male avatar 73', '/avatars/male/avatar_073.png', array['personnel']::public.icon_entity_type[], '{male}', 1073, 'male'),
  ('avatar-male-074', 'Male avatar 74', '/avatars/male/avatar_074.png', array['personnel']::public.icon_entity_type[], '{male}', 1074, 'male'),
  ('avatar-male-076', 'Male avatar 76', '/avatars/male/avatar_076.png', array['personnel']::public.icon_entity_type[], '{male}', 1076, 'male'),
  ('avatar-male-077', 'Male avatar 77', '/avatars/male/avatar_077.png', array['personnel']::public.icon_entity_type[], '{male}', 1077, 'male'),
  ('avatar-male-085', 'Male avatar 85', '/avatars/male/avatar_085.png', array['personnel']::public.icon_entity_type[], '{male}', 1085, 'male'),
  ('avatar-male-086', 'Male avatar 86', '/avatars/male/avatar_086.png', array['personnel']::public.icon_entity_type[], '{male}', 1086, 'male'),
  ('avatar-male-087', 'Male avatar 87', '/avatars/male/avatar_087.png', array['personnel']::public.icon_entity_type[], '{male}', 1087, 'male'),
  ('avatar-male-088', 'Male avatar 88', '/avatars/male/avatar_088.png', array['personnel']::public.icon_entity_type[], '{male}', 1088, 'male'),
  ('avatar-male-089', 'Male avatar 89', '/avatars/male/avatar_089.png', array['personnel']::public.icon_entity_type[], '{male}', 1089, 'male'),
  ('avatar-male-090', 'Male avatar 90', '/avatars/male/avatar_090.png', array['personnel']::public.icon_entity_type[], '{male}', 1090, 'male'),
  ('avatar-male-091', 'Male avatar 91', '/avatars/male/avatar_091.png', array['personnel']::public.icon_entity_type[], '{male}', 1091, 'male'),
  ('avatar-male-092', 'Male avatar 92', '/avatars/male/avatar_092.png', array['personnel']::public.icon_entity_type[], '{male}', 1092, 'male'),
  ('avatar-male-093', 'Male avatar 93', '/avatars/male/avatar_093.png', array['personnel']::public.icon_entity_type[], '{male}', 1093, 'male'),
  ('avatar-male-094', 'Male avatar 94', '/avatars/male/avatar_094.png', array['personnel']::public.icon_entity_type[], '{male}', 1094, 'male'),
  ('avatar-male-095', 'Male avatar 95', '/avatars/male/avatar_095.png', array['personnel']::public.icon_entity_type[], '{male}', 1095, 'male'),
  ('avatar-male-096', 'Male avatar 96', '/avatars/male/avatar_096.png', array['personnel']::public.icon_entity_type[], '{male}', 1096, 'male'),
  ('avatar-male-098', 'Male avatar 98', '/avatars/male/avatar_098.png', array['personnel']::public.icon_entity_type[], '{male}', 1098, 'male'),
  ('avatar-female-002', 'Female avatar 2', '/avatars/female/avatar_002.png', array['personnel']::public.icon_entity_type[], '{female}', 2002, 'female'),
  ('avatar-female-004', 'Female avatar 4', '/avatars/female/avatar_004.png', array['personnel']::public.icon_entity_type[], '{female}', 2004, 'female'),
  ('avatar-female-005', 'Female avatar 5', '/avatars/female/avatar_005.png', array['personnel']::public.icon_entity_type[], '{female}', 2005, 'female'),
  ('avatar-female-007', 'Female avatar 7', '/avatars/female/avatar_007.png', array['personnel']::public.icon_entity_type[], '{female}', 2007, 'female'),
  ('avatar-female-010', 'Female avatar 10', '/avatars/female/avatar_010.png', array['personnel']::public.icon_entity_type[], '{female}', 2010, 'female'),
  ('avatar-female-013', 'Female avatar 13', '/avatars/female/avatar_013.png', array['personnel']::public.icon_entity_type[], '{female}', 2013, 'female'),
  ('avatar-female-015', 'Female avatar 15', '/avatars/female/avatar_015.png', array['personnel']::public.icon_entity_type[], '{female}', 2015, 'female'),
  ('avatar-female-017', 'Female avatar 17', '/avatars/female/avatar_017.png', array['personnel']::public.icon_entity_type[], '{female}', 2017, 'female'),
  ('avatar-female-018', 'Female avatar 18', '/avatars/female/avatar_018.png', array['personnel']::public.icon_entity_type[], '{female}', 2018, 'female'),
  ('avatar-female-019', 'Female avatar 19', '/avatars/female/avatar_019.png', array['personnel']::public.icon_entity_type[], '{female}', 2019, 'female'),
  ('avatar-female-020', 'Female avatar 20', '/avatars/female/avatar_020.png', array['personnel']::public.icon_entity_type[], '{female}', 2020, 'female'),
  ('avatar-female-025', 'Female avatar 25', '/avatars/female/avatar_025.png', array['personnel']::public.icon_entity_type[], '{female}', 2025, 'female'),
  ('avatar-female-027', 'Female avatar 27', '/avatars/female/avatar_027.png', array['personnel']::public.icon_entity_type[], '{female}', 2027, 'female'),
  ('avatar-female-028', 'Female avatar 28', '/avatars/female/avatar_028.png', array['personnel']::public.icon_entity_type[], '{female}', 2028, 'female'),
  ('avatar-female-043', 'Female avatar 43', '/avatars/female/avatar_043.png', array['personnel']::public.icon_entity_type[], '{female}', 2043, 'female'),
  ('avatar-female-044', 'Female avatar 44', '/avatars/female/avatar_044.png', array['personnel']::public.icon_entity_type[], '{female}', 2044, 'female'),
  ('avatar-female-045', 'Female avatar 45', '/avatars/female/avatar_045.png', array['personnel']::public.icon_entity_type[], '{female}', 2045, 'female'),
  ('avatar-female-046', 'Female avatar 46', '/avatars/female/avatar_046.png', array['personnel']::public.icon_entity_type[], '{female}', 2046, 'female'),
  ('avatar-female-047', 'Female avatar 47', '/avatars/female/avatar_047.png', array['personnel']::public.icon_entity_type[], '{female}', 2047, 'female'),
  ('avatar-female-048', 'Female avatar 48', '/avatars/female/avatar_048.png', array['personnel']::public.icon_entity_type[], '{female}', 2048, 'female'),
  ('avatar-female-049', 'Female avatar 49', '/avatars/female/avatar_049.png', array['personnel']::public.icon_entity_type[], '{female}', 2049, 'female'),
  ('avatar-female-050', 'Female avatar 50', '/avatars/female/avatar_050.png', array['personnel']::public.icon_entity_type[], '{female}', 2050, 'female'),
  ('avatar-female-051', 'Female avatar 51', '/avatars/female/avatar_051.png', array['personnel']::public.icon_entity_type[], '{female}', 2051, 'female'),
  ('avatar-female-052', 'Female avatar 52', '/avatars/female/avatar_052.png', array['personnel']::public.icon_entity_type[], '{female}', 2052, 'female'),
  ('avatar-female-053', 'Female avatar 53', '/avatars/female/avatar_053.png', array['personnel']::public.icon_entity_type[], '{female}', 2053, 'female'),
  ('avatar-female-054', 'Female avatar 54', '/avatars/female/avatar_054.png', array['personnel']::public.icon_entity_type[], '{female}', 2054, 'female'),
  ('avatar-female-055', 'Female avatar 55', '/avatars/female/avatar_055.png', array['personnel']::public.icon_entity_type[], '{female}', 2055, 'female'),
  ('avatar-female-056', 'Female avatar 56', '/avatars/female/avatar_056.png', array['personnel']::public.icon_entity_type[], '{female}', 2056, 'female'),
  ('avatar-female-058', 'Female avatar 58', '/avatars/female/avatar_058.png', array['personnel']::public.icon_entity_type[], '{female}', 2058, 'female'),
  ('avatar-female-062', 'Female avatar 62', '/avatars/female/avatar_062.png', array['personnel']::public.icon_entity_type[], '{female}', 2062, 'female'),
  ('avatar-female-063', 'Female avatar 63', '/avatars/female/avatar_063.png', array['personnel']::public.icon_entity_type[], '{female}', 2063, 'female'),
  ('avatar-female-072', 'Female avatar 72', '/avatars/female/avatar_072.png', array['personnel']::public.icon_entity_type[], '{female}', 2072, 'female'),
  ('avatar-female-075', 'Female avatar 75', '/avatars/female/avatar_075.png', array['personnel']::public.icon_entity_type[], '{female}', 2075, 'female'),
  ('avatar-female-078', 'Female avatar 78', '/avatars/female/avatar_078.png', array['personnel']::public.icon_entity_type[], '{female}', 2078, 'female'),
  ('avatar-female-079', 'Female avatar 79', '/avatars/female/avatar_079.png', array['personnel']::public.icon_entity_type[], '{female}', 2079, 'female'),
  ('avatar-female-080', 'Female avatar 80', '/avatars/female/avatar_080.png', array['personnel']::public.icon_entity_type[], '{female}', 2080, 'female'),
  ('avatar-female-081', 'Female avatar 81', '/avatars/female/avatar_081.png', array['personnel']::public.icon_entity_type[], '{female}', 2081, 'female'),
  ('avatar-female-082', 'Female avatar 82', '/avatars/female/avatar_082.png', array['personnel']::public.icon_entity_type[], '{female}', 2082, 'female'),
  ('avatar-female-083', 'Female avatar 83', '/avatars/female/avatar_083.png', array['personnel']::public.icon_entity_type[], '{female}', 2083, 'female'),
  ('avatar-female-084', 'Female avatar 84', '/avatars/female/avatar_084.png', array['personnel']::public.icon_entity_type[], '{female}', 2084, 'female'),
  ('avatar-female-097', 'Female avatar 97', '/avatars/female/avatar_097.png', array['personnel']::public.icon_entity_type[], '{female}', 2097, 'female'),
  ('avatar-female-099', 'Female avatar 99', '/avatars/female/avatar_099.png', array['personnel']::public.icon_entity_type[], '{female}', 2099, 'female'),
  ('avatar-female-100', 'Female avatar 100', '/avatars/female/avatar_100.png', array['personnel']::public.icon_entity_type[], '{female}', 2100, 'female'),
  ('avatar-female-101', 'Female avatar 101', '/avatars/female/avatar_101.png', array['personnel']::public.icon_entity_type[], '{female}', 2101, 'female'),
  ('avatar-female-102', 'Female avatar 102', '/avatars/female/avatar_102.png', array['personnel']::public.icon_entity_type[], '{female}', 2102, 'female'),
  ('avatar-female-103', 'Female avatar 103', '/avatars/female/avatar_103.png', array['personnel']::public.icon_entity_type[], '{female}', 2103, 'female'),
  ('avatar-female-104', 'Female avatar 104', '/avatars/female/avatar_104.png', array['personnel']::public.icon_entity_type[], '{female}', 2104, 'female'),
  ('avatar-female-105', 'Female avatar 105', '/avatars/female/avatar_105.png', array['personnel']::public.icon_entity_type[], '{female}', 2105, 'female'),
  ('avatar-female-106', 'Female avatar 106', '/avatars/female/avatar_106.png', array['personnel']::public.icon_entity_type[], '{female}', 2106, 'female'),
  ('avatar-female-107', 'Female avatar 107', '/avatars/female/avatar_107.png', array['personnel']::public.icon_entity_type[], '{female}', 2107, 'female'),
  ('avatar-female-108', 'Female avatar 108', '/avatars/female/avatar_108.png', array['personnel']::public.icon_entity_type[], '{female}', 2108, 'female'),
  ('avatar-female-109', 'Female avatar 109', '/avatars/female/avatar_109.png', array['personnel']::public.icon_entity_type[], '{female}', 2109, 'female'),
  ('avatar-female-110', 'Female avatar 110', '/avatars/female/avatar_110.png', array['personnel']::public.icon_entity_type[], '{female}', 2110, 'female'),
  ('avatar-female-111', 'Female avatar 111', '/avatars/female/avatar_111.png', array['personnel']::public.icon_entity_type[], '{female}', 2111, 'female'),
  ('avatar-female-112', 'Female avatar 112', '/avatars/female/avatar_112.png', array['personnel']::public.icon_entity_type[], '{female}', 2112, 'female');

update public.personnel
set
  icon_id = 'avatar-female-002',
  avatar_gender = 'female'
where icon_id in ('person-default', 'person-01', 'person-02', 'person-03', 'person-04', 'person-05', 'person-06', 'person-07', 'person-08', 'person-09', 'person-10', 'person-11');

alter table public.personnel
  alter column icon_id set default 'avatar-female-002';

delete from public.app_icons
where id in ('person-default', 'person-01', 'person-02', 'person-03', 'person-04', 'person-05', 'person-06', 'person-07', 'person-08', 'person-09', 'person-10', 'person-11');
