insert into public.role_permissions (role, permission)
values
  ('developer_admin', 'platform.users.read'),
  ('developer_admin', 'platform.users.update'),
  ('developer_admin', 'platform.users.delete'),
  ('developer_admin', 'platform.tenants.read'),
  ('developer_admin', 'platform.tenants.update'),
  ('developer_admin', 'platform.tenants.delete'),
  ('developer_admin', 'platform.records.hard_delete'),
  ('developer_admin', 'organization.update'),
  ('developer_admin', 'users.invite'),
  ('developer_admin', 'users.disable'),
  ('developer_admin', 'roles.manage'),
  ('developer_admin', 'locations.manage'),
  ('developer_admin', 'personnel.manage'),
  ('developer_admin', 'shifts.read'),
  ('developer_admin', 'shifts.create'),
  ('developer_admin', 'shifts.update'),
  ('developer_admin', 'shifts.delete'),
  ('developer_admin', 'shifts.assign'),
  ('developer_admin', 'notes.read'),
  ('developer_admin', 'notes.create'),
  ('developer_admin', 'notes.update'),
  ('developer_admin', 'notes.delete'),
  ('developer_admin', 'notes.acknowledge'),
  ('developer_admin', 'notifications.manage')
on conflict do nothing;
